#!/usr/bin/env bash

for file in $(ls videos/incoming/*.MP4); do
    if [ ! -f "$file.json" ]; then
        echo "Computing for $file"
        pipenv run python create_object_information.py --input $file  --threshold=0.2 --filter_threshold=0.2 --nodisplay
    fi
done
